# Generated by Django 5.2.3 on 2025-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_booking_customer_email_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='dks', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
