services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: alxtravelapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    mem_limit: 512m

  app:
    build: .
    expose:
      - "8600"   # expose port only to Docker network, not to host
    environment:
      - CELERY_BROKER_URL=amqp://user:1qaz@rabbitmq:5672//
      - DEBUG=True
      - DB_NAME=alxtravelapp
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=1qaz2wsx
      - DB_USER=postgres
      - EMAIL_HOST_USER='hackinglife959@gmail.com'
      - EMAIL_HOST_PASSWORD='dccygwnnzmluqcgi'
      - CHAPA_SECRET_KEY=CHASECK_TEST-zEsmDdWNz4r799ntOnjbPMmZOarYhA2G
    command: >
      bash -c "
      sleep 30 
      && python manage.py migrate 
      && python manage.py collectstatic --noinput 
      && gunicorn alx_travel_app.wsgi:application --bind 0.0.0.0:8600
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1qaz
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    build: .
    command: celery -A alx_travel_app worker --pool=solo -l info
    environment:
      - CELERY_BROKER_URL=amqp://user:1qaz@rabbitmq:5672//
      - DEBUG=True
      - DB_NAME=alxtravelapp
      - DB_HOST=db
      - DB_PORT=5436
      - DB_PASSWORD=1qaz2wsx
      - DB_USER=postgres
      - EMAIL_HOST_USER='hackinglife959@gmail.com'
      - EMAIL_HOST_PASSWORD='dccygwnnzmluqcgi'
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # expose port 80 to the host machine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local