services:
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: alxtravelapp
            MYSQL_ROOT_PASSWORD: 1QAZ2wsx@
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3336:3306"

    app:
        build: .
        ports:
            - "8600:8600"
        environment:
            - DEBUG=True
            - DB_NAME=alxtravelapp
            - DB_HOST=db
            - DB_PORT=3306
            - DB_PASSWORD=1QAZ2wsx@
            - DB_USER=root
            - CHAPA_SECRET_KEY=CHASECK_TEST-zEsmDdWNz4r799ntOnjbPMmZOarYhA2G
        command: >
            bash -c "
            sleep 30 
            && python manage.py migrate 
            && python manage.py collectstatic --noinput 
            && gunicorn alx_travel_app.wsgi:application --bind 0.0.0.0:8600
            "
        volumes:
            - .:/app
        depends_on:
            - db
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "15672:15672"
            - "5672:5672"

volumes:
    mysql_data:
        driver: local
